import { Platform } from "react-native";
import { exploreColors } from "~/lib/exploreDesign";

/** Shared dimensions for My Matches + Explore list cards. */
export const MATCH_LIST_CARD = {
  accentWidth: 5,
  cardWidthPercent: "96.4%",
  cardMarginBottom: 12,
  cardRadius: 18,
  padH: 14,
  padTop: 12,
  padBottom: 12,
  headerMb: 10,
  headerGap: 6,
  avatar: 38,
  avatarRadius: 9,
  avatarFont: 10,
  avatarMr: 10,
  rowPy: 8,
  dividerMv: 0,
  playerName: 13,
  scoreColW: 24,
  scoreColWCompact: 20,
  scoreColWDense: 17,
  scoreColGap: 8,
  scoreColGapTight: 5,
  scoreFont: 14,
  scoreFontCompact: 12,
  scoreHeaderPt: 5,
  scoreHeaderPb: 4,
  scoreLabel: 8,
  scoreboardMb: 2,
  badgePadH: 8,
  badgePadV: 4,
  badgeRadius: 8,
  badgeGap: 4,
  badgeFont: 8,
  liveDot: 5,
  listBadgePadH: 8,
  listBadgePadV: 4,
  listBadgeFont: 8,
  listBadgeRadius: 8,
  publicIcon: 9,
  inlineGap: 5,
  inlineMt: 6,
  inlineMb: 4,
  scheduledFont: 10,
  scheduledIcon: 12,
  noteFont: 9,
  winnerFont: 9,
  trophyIcon: 10,
  footerMt: 10,
  footerPt: 10,
  footerIcon: 10,
  footerFont: 9,
  footerIconMr: 5,
  footerActionsGap: 12,
  heartIcon: 14,
  heartFont: 9,
  reportIcon: 12,
  reportFont: 9,
  actionMinH: 24,
  actionPy: 5,
  actionFont: 11,
  actionCompleteFont: 11,
  actionIcon: 12,
  actionMt: 5,
  actionMb: 3,
  actionRadius: 8,
  actionGap: 5,
  actionRowMt: 5,
  /** Legacy MatchCard / PublicMatchCard / MatchListCardScore */
  accentHeight: 2,
  rowGap: 4,
  winner: 9,
  sectionGap: 6,
  avatarRing: 39,
  avatarInner: 34,
  winnerRing: 2,
  vs: 8,
  meta: 8,
  scoreChipPadH: 7,
  scoreChipPadV: 4,
  emptyScorePadH: 8,
  emptyScorePadV: 6,
} as const;

const matchListCardElevation = Platform.select({
  ios: {
    shadowColor: exploreColors.cardShadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 14,
  },
  android: { elevation: 4 },
  default: {
    shadowColor: exploreColors.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
  },
});

export const matchListCardShell = {
  width: MATCH_LIST_CARD.cardWidthPercent,
  alignSelf: "center" as const,
  marginBottom: MATCH_LIST_CARD.cardMarginBottom,
  borderRadius: MATCH_LIST_CARD.cardRadius,
  backgroundColor: exploreColors.cardBg,
  borderWidth: 1,
  borderColor: exploreColors.cardBorderHairline,
  overflow: "hidden" as const,
  ...matchListCardElevation,
};

export const matchListCardInner = {
  flex: 1,
  paddingHorizontal: MATCH_LIST_CARD.padH,
  paddingTop: MATCH_LIST_CARD.padTop,
  paddingBottom: MATCH_LIST_CARD.padBottom,
};

export const matchListCardFooterStyle = {
  borderTopWidth: 1,
  borderTopColor: exploreColors.cardBorderHairline,
  marginTop: MATCH_LIST_CARD.footerMt,
  paddingTop: MATCH_LIST_CARD.footerPt,
  flexDirection: "row" as const,
  alignItems: "center" as const,
  justifyContent: "space-between" as const,
};

export const matchListCardHeaderStyle = {
  flexDirection: "row" as const,
  alignItems: "center" as const,
  justifyContent: "space-between" as const,
  marginBottom: MATCH_LIST_CARD.headerMb,
};

export const matchListLeadingWidth = MATCH_LIST_CARD.avatar + MATCH_LIST_CARD.avatarMr;
